#import "template.typ": card, flashcards

#set page(margin: 1cm)
#set text(size: 15pt)

#show text.where(lang: "en"): set text(font: "IBM Plex Sans")
#show text.where(lang: "jp"): set text(font: "Hiragino Sans")

#let definitions = (
  card([meet], [あいます]),
  card([morning], [あさ]),
  card([breakfast], [あさごほん]),
  card([after], [あと]),
  card([take (a shower)], [あびます]),
  card([Africa], [アフリカ], jinfo: [あふりか]),
  card([go], [いきます], jinfo: [行きます]),
  card([when], [いつ]),
  card([always], [いつも]),
  card([song], [うた]),
  card([house, home], [うち]),
  card([wake up, get up], [おきます]),
  card([swim], [およぎます]),
  card([music], [おんがく]),
  card([buy], [かいます]),
  card([shopping], [かいもの]),
  card([return], einfo: [shopping], [かえります]),
  card([write], [かきます]),
  card([curry], [カレー], jinfo: [かれー]),
  card([Korean], einfo: [language], [かんこくご]),
  card([Korean food], [かんこく りょうり]),
  card([listen to, hear], [ききます]),
  card([ticket], [きっぷ]),
  card([come], [きます]),
  card([classroom], [きょうしつ]),
  card([cake], [ケーキ], jinfo: [けーき]),
  card([coffee], [コーヒー], jinfo: [こーひー]),
  card([around, about], info: [time], [〜ごろ]),
  card([soccer], [サッカー], jinfo: [さっかー]),
  card([salad], [サラド], jinfo: [さらど]),
  card([do], [〜します]),
  card([shower], [シャワー], jinfo: [じゃわー]),
  card([juice], [ジュース], jinfo: [じゅーす]),
  card([homework], [しゅうだい]),
  card([sports], [スポーツ], jinfo: [すぽーつ]),
  card([then], [それから]),
  card([usually], [たいてい]),
  card([taxi], [タクシー], jinfo: [たくしー]),
  card([look fun], [たのしそう(な)]),
  card([eat], [たべます], jinfo: [食べます]),
  card([egg], [たまご]),
  card([occasionally], [たまに]),
  card([Chinese food], [ちゅうかりょうり]),
  card([Germany], [ドイツ], jinfo: [どいつ]),
  card([how, in what way], [どうやって]),
  card([sometimes], [ときどき]),
  card([sleep, go to bed], [ねます]),
  card([drink], [のみます]),
  card([get on, board, ride], [のります]),
  card([BBQ], [バーベキュー], jinfo: [ばーべきゅー]),
  card([postcard], [はがき]),
  card([bus], [バス], jinfo: [ばす]),
  card([pasta], [パスタ], jinfo: [ぱすた]),
  card([early, fast, quick], [はやい]),
  card([bread], [パン], jinfo: [ぱん]),
  card([dinner], [ばんごはん]),
  card([lunch], [ひるごはん]),
  card([study], [べんきょうします]),
  card([every week], [まいしゅう]),
  card([every month], [まいつき]),
  card([every day], [まいにち]),
  card([watch, see, look], [みます]),
  card([often, frequently], [よく]),
  card([read], [よみます]),
  card([night], [よる]),
  card([rugby], [ラグビー], jinfo: [らぐびー]),
  card([London], [ロンドン], jinfo: [ろんどん]),
  card([wine], [ワイン], jinfo: [わいん]),
  card([understand, know], [わかります]),
  card([laugh, smile], [わります]),
  card([Monday], [げつようび], jinfo: [月曜日]),
  card([Tuesday], [かようび], jinfo: [火曜日]),
  card([Wednesday], [すいようび], jinfo: [水曜日]),
  card([Thursday], [もくようび], jinfo: [木曜日]),
  card([Friday], [きんようび], jinfo: [金曜日]),
  card([Saturday], [どようび], jinfo: [土曜日]),
  card([Sunday], [にちようび], jinfo: [日曜日]),
)


#flashcards(
  lang: (front: "en", back: "jp"),
  definitions,
  card: (
    width: 91mm,
    height: 55mm,
  ),
)
