#import "../template.typ": card, flashcards

#set page(margin: 1cm, numbering: "1 of 1")
#set text(size: 15pt)


#let definitions = (
  card([tomorrow], [あした], jinfo: [明日]),
  card([over there], [あそこ]),
  card([exist, be], einfo: [inanimate], [あります]),
  card([part-time job], [アルバイト]),
  card([chair], [いす]),
  card([dog], [いぬ], jinfo: [犬]),
  card([exist, be], einfo: [animate], [います]),
  card([younger sister], [いもうと]),
  card([on, above], [うえ], jinfo: [上]),
  card([behind], [うしろ]),
  card([Egypt], [エジプト]),
  card([money], [おかね]),
  card([older brother], [おにさん], jinfo: [お兄さん]),
  card([older sister], [おねえさん], jinfo: [お姉さん]),
  card([office], [オフィス]),
  card([Opera House], [オペラハラス]),
  card([school], [がっこう], jinfo: [学校]),
  card([cup], [カップ]),
  card([coffee shop], [きっさてん]),
  card([Canberra], [チャンベラ]),
  card([today], [きょう], jinfo: [今日]),
  card([siblings], [きょうだい]),
  card([Kyoto], [きょうと]),
  card([shoe shop], [くつや]),
  card([mobile phone], [けたいでんわ]),
  card([park], [こうえん]),
  card([here], [ここ]),
  card([Parliament House], [こっかいぎじどう]),
  card([next time], [こんど]),
  card([tonight], [こんばん]),
  card([computer], [コンピューター]),
  card([Sapporo], [さっぽろ]),
  card([time], [じかん]),
  card([under, beneath], [した], jinfo: [下]),
  card([bicycle], [じてんしゃ]),
  card([weekend], [しゅうまつ]),
  card([Singapore], [シンガポール]),
  card([there], [そこ]),
  card([near], [そば]),
  card([sofa], [ソファ]),
  card([Thai], [タイ]),
  card([building], [たてもの]),
  card([desk], [つくえ]),
  card([table], [テーブル]),
  card([test, exam], [テスト]),
  card([department store], [デパート]),
  card([TV], [テレビ]),
  card([telephone], [でんわ]),
  card([next, next to], [となり]),
  card([inside], [なか]),
  card([cat], [ねこ]),
  card([box], [はこ]),
  card([bus stop], [バスてい]),
  card([Pyramid], [ピラミッド]),
  card([Brisbane], [ブリスベン]),
  card([room], [へや]),
  card([bookshop], [ほんや]),
  card([front, in front of], [まえ]),
  card([manga], [まんが]),
  card([glasses], [めがね]),
  card([Melbourne], [メルボルン]),
  card([post office], [ゆうびんきょう]),
  card([radio], [ラジオ]),
  card([apple], [りんご]),
  card([restaurant], [レストラン]),
  card(
    [could you say it again],
    einfo: [casual],
    [もう　いちどう　いって　もらえませんか],
  ),
  card(
    [could you say it again],
    einfo: [formal],
    [もう　いちどう　いって　いただけませんか],
  ),
  card(
    [could you speak slowly please],
    einfo: [casual],
    [ゆっくり　いって　もらえませんか],
  ),
  card(
    [could you speak slowly please],
    einfo: [formal],
    [ゆっくり　いって　いただけませんか],
  ),
  card([how do you say 'x' in english], [「x」　って　えいごで　何ですか]),
)


#flashcards(
  lang: (front: "en", back: "jp"),
  definitions,
  card: (
    width: 91mm,
    height: 55mm,
  ),
)
