#import "../template.typ": card, flashcards, kata

#set page(margin: 1cm)
#set text(size: 15pt)

#let definitions = (
  card([blue], [あおい]),
  card([red], [あかい]),
  card([leg, foot], [あし]),
  card([warm], [あたたかい]),
  card([information lady], [あんないじょう]),
  card([new], [あたらしい]),
  card([not very...], [あまり]),
  card([how much], [いくら]),
  card([sore, hurt], [いたい]),
  card([various], [いろいろ]),
  card([glad], [うれしい]),
  card([sales section], [うりば]),
  card([escalator], kata[エスカレーター][えすかれーたー]),
  card([elevator], kata[エレベーター][えれべーたー]),
  card([big, large], [おおきい]),
  card([customer], einfo: [guest, visitor, client], [おきゃくさん]),
  card([bathroom], [おてあらい]),
  card([heavy], [おもい]),
  card([interesting], [おもしろい]),
  card([~th floor], [〜かい]),
  card([stairs], [かいだん]),
  card([furniture], [かぐ]),
  card([singer], [かしゅ]),
  card([wind], [かぜ]),
  card([sad], [かなしい]),
  card([hair], [かみのけ]),
  card([cute], [かわいい]),
  card([pitiful], [かわいそう（な）]),
  card([easy], einfo: [simple], [かんたん（な）]),
  card([yellow], [きいろい]),
  card([strict], [きびしい]),
  card([feel good], [きもちがいい]),
  card([pretty], einfo: [clean], [きれい（な）]),
  card([black], [くろい]),
  card([cosmetics], [けしょうひん]),
  card([healthy], [げんき（な）]),
  card([exists], einfo: [formal], [ございます]),
  card([scary], einfo: [afraid], [こわい]),
  card([cherry blossom], [さくら]),
  card([quiet], [しずか（な）]),
  card([jacket], kata[ジャケット][じゃけっと]),
  card([photo], [しゃしん]),
  card([shirt], kata[シャツ][しゃつ]),
  card([good at], einfo: [skilled], [じょうず（な）]),
  card([meal], [しょくじ]),
  card([groceries], einfo: [food], [しょくりょうひん]),
  card([kind], einfo: [gentle], [しんせつ（な）]),
  card([white], [しろい]),
  card([men's clothes], [しんしふく]),
  card([skirt], kata[スカート][すかーと]),
  card([sweater], kata[セーター][せーたー]),
  card([tall], [せがたかい]),
  card([boring], [たいくつ（な）]),
  card([it's okay], [だいじょうぶ（な）]),
  card([fun], [たのしい]),
  card([small], einfo: [little], [ちいさい]),
  card([underground], [ちか]),
  card([close], [ちかい]),
  card([car park], [ちゅうしゃじょう]),
  card([just], [ちょうど]),
  card([leaflet], [ちらし]),
  card([strong], [つよい]),
  card([electronic goods], [でんきせいひん]),
  card([toilets], kata[トイレ][といれ]),
  card([how], [どう]),
  card([far], [とおい]),
  card([characteristics], [とくちょう]),
  card([place], [ところ]),
  card([very], [とても]),
  card([take], [とります]),
  card([long], [ながい]),
  card([vivid], [にぎやか（な）]),
  card([nose], [はな]),
  card([fast], [はやい]),
  card([beach], kata[ビーチ][びーち]),
  card([beer], kata[ビール][びーる]),
  card([left], [ひだり]),
  card([wide], einfo: [spacious], [ひろい]),
  card([Mt. Fuji], [ふじさん]),
  card([women's clothes], [ふじんふく]),
  card([old], [ふろい]),
  card([stationary], [ぶんぼうぐ]),
  card([again], [また]),
  card([festival], [まつ]),
  card([right], [みぎ]),
  card([ear], [みみ]),
  card([hard], einfo: [difficult], [むずかしい]),
  card([eye], [め]),
  card([thing], einfo: [item], [もの]),
  card([more], [もっと]),
  card([Japanese BBQ], [やきにく]),
  card([cheap], [やすい]),
  card([famous], [ゆうめい（な）]),
  card([side], [よこ]),
  card([next year], [らいねん]),
  card([comfortable], [らく（な）]),
  card([travel], einfo: [trip], [りょこう]),
)

#flashcards(
  lang: (front: "en", back: "jp"),
  definitions,
  card: (
    width: 91mm,
    height: 55mm,
  ),
)
