name: Typst Format

on:
  pull_request:
    branches:
      - main
    paths:
      - "*.typ"

jobs:
  typstyle:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Fetch PR branch
        run: |
          gh pr checkout ${{ github.event.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run typstyle
        uses: typstyle-rs/typstyle-action@main
        with:
          opts: "--check"
