name: Typst Format

on:
  pull_request:
    branches:
      - main
    paths:
      - "*.typ"

jobs:
  typstyle:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          path: pull-request
      - name: Run typstyle
        uses: typstyle-rs/typstyle-action@main
        with:
          opts: "--check"
